version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: tienda_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_seguro
      POSTGRES_DB: tienda_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tienda_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password_seguro@db:5432/tienda_db
      - SECRET_KEY=CAMBIA_ESTA_CLAVE_POR_ALGO_LARGO_Y_SEGURO_123456789
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  postgres_data:
