"""initial

Revision ID: 44a86e37df96
Revises: 
Create Date: 2026-02-26 00:40:32.959824
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a86e37df96'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiendas',
    sa.Column('id_tienda', sa.UUID(), nullable=False),
    sa.Column('nombre_tienda', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('dominio_personalizado', sa.String(length=100), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_tienda'),
    sa.UniqueConstraint('dominio_personalizado')
    )
    op.create_index(op.f('ix_tiendas_slug'), 'tiendas', ['slug'], unique=True)
    op.create_table('categorias',
    sa.Column('id_categoria', sa.UUID(), nullable=False),
    sa.Column('id_tienda', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_tienda'], ['tiendas.id_tienda'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('clientes',
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('id_tienda', sa.UUID(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('ciudad_region', sa.String(length=100), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_tienda'], ['tiendas.id_tienda'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('id_tienda', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_tienda'], ['tiendas.id_tienda'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('id_tienda', sa.UUID(), nullable=False),
    sa.Column('id_categoria', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_adquisicion', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_agregado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_tienda'], ['tiendas.id_tienda'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('ventas',
    sa.Column('id_venta', sa.UUID(), nullable=False),
    sa.Column('id_tienda', sa.UUID(), nullable=False),
    sa.Column('id_cliente', sa.UUID(), nullable=True),
    sa.Column('fecha_venta', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('total_venta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_tienda'], ['tiendas.id_tienda'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('detalle_ventas',
    sa.Column('id_detalle', sa.UUID(), nullable=False),
    sa.Column('id_venta', sa.UUID(), nullable=False),
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_ventas')
    op.drop_table('ventas')
    op.drop_table('productos')
    op.drop_table('usuarios')
    op.drop_table('clientes')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_tiendas_slug'), table_name='tiendas')
    op.drop_table('tiendas')
    # ### end Alembic commands ###
