"""Add_rol_usuario_to_audit_logs

Revision ID: 7ffb0ddfe4e1
Revises: c2d660c49fbc
Create Date: 2026-07-22 03:56:50.083858
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ffb0ddfe4e1'
down_revision: Union[str, None] = 'c2d660c49fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('rol_usuario', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'rol_usuario')
    # ### end Alembic commands ###
