"""add_origen_to_ventas

Revision ID: c2d660c49fbc
Revises: a1b2c3d4e6f7
Create Date: 2026-07-20 17:23:34.298048
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2d660c49fbc'
down_revision: Union[str, None] = 'a1b2c3d4e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('origen', sa.String(length=50), nullable=True))
    op.alter_column('ventas', 'estado',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('generada_whatsapp', 'pendiente', 'completada', 'cancelada', name='estado_venta_enum', native_enum=False),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ventas', 'estado',
               existing_type=sa.Enum('generada_whatsapp', 'pendiente', 'completada', 'cancelada', name='estado_venta_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('ventas', 'origen')
    # ### end Alembic commands ###
